package eg.edu.alexu.csd.oop.jdbc.cs24;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public class MyStatement implements Statement {

	public <T> T unwrap(Class<T> iface) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public ResultSet executeQuery(String sql) throws SQLException {

		return null;
	}

	
	public int executeUpdate(String sql) throws SQLException {

		return 0;
	}

	
	public void close() throws SQLException {


	}

	
	public int getMaxFieldSize() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setMaxFieldSize(int max) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getMaxRows() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setMaxRows(int max) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setEscapeProcessing(boolean enable) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getQueryTimeout() throws SQLException {

		return 0;
	}

	
	public void setQueryTimeout(int seconds) throws SQLException {


	}

	
	public void cancel() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public SQLWarning getWarnings() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void clearWarnings() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setCursorName(String name) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean execute(String sql) throws SQLException {

		return false;
	}

	
	public ResultSet getResultSet() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getUpdateCount() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean getMoreResults() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setFetchDirection(int direction) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getFetchDirection() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setFetchSize(int rows) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getFetchSize() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getResultSetConcurrency() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getResultSetType() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void addBatch(String sql) throws SQLException {


	}

	
	public void clearBatch() throws SQLException {


	}

	
	public int[] executeBatch() throws SQLException {

		return null;
	}

	
	public Connection getConnection() throws SQLException {

		return null;
	}

	
	public boolean getMoreResults(int current) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public ResultSet getGeneratedKeys() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public int getResultSetHoldability() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean isClosed() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void setPoolable(boolean poolable) throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean isPoolable() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public void closeOnCompletion() throws SQLException {
		throw new UnsupportedOperationException();
	}

	
	public boolean isCloseOnCompletion() throws SQLException {
		throw new UnsupportedOperationException();
	}

}
